### ISSUE TITLE
Addresses not loading HK region

### ISSUE THREAD

**Issue by aliutiev** [droplinked/issues#1]
<img width="724" alt="image" src="https://github.com/droplinked/issues/assets/45078400/6c7a68cb-7af6-4399-8ea4-d855e6db7aad">

- no options
- not a postal code, should change from zip code to postal

**Comment by behdadmns** [comment]
Thank you for the report you provided. The East Asia address database has not yet been completed, so we are currently considering the address as an optional field, allowing users to create their store without entering an address.
@aliutiev
