### ISSUE TITLE
Adjust this feature

### ISSUE THREAD

**Issue by aliutiev** [droplinked/issues#4]
This would look much better if it was either a 3-5 option color picker + a custom color picker or just the color picker on it's own. I understand the thought process here behind providing options but it comes off as very low quality with the different coloured outlines and options.

<img width="1036" alt="image" src="https://github.com/droplinked/issues/assets/45078400/4df3f4ee-801a-4ca0-825a-2f1618b6778f">

**Comment by nokhodian** [comment]
we can not pick any color, colors are offered by print provider and in some cases there are variety of options which we want to make sure show owners see them all.
