### ISSUE TITLE
Enhancement Request: Give users the option to adjust their logo size

### ISSUE THREAD

**Issue by aliutiev** [droplinked/issues#8]
<img width="1434" alt="image" src="https://github.com/droplinked/issues/assets/45078400/da0a0108-4a86-46da-8925-9d4c52878df7">

**Comment by nokhodian** [comment]
unfortunately on current shop builder we can't add this option, customers should ask for custom template for this

**Comment by nokhodian** [comment]
**Code verified — status: not confirmed implemented.**

No logo size adjustment setting was found in the current shop-builder settings. The `AppLogo` component renders with a fixed `height='45px'`.

**What's next:**
- Add a logo size/scale setting to shop settings (ShopDesign or ShopSettings)
- Expose it in the shop-builder Settings → Appearance page
- Apply the value in `AppLogo.tsx` as a dynamic `height` prop

Monotask card added to Backlog / Refactor on the board.
